# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BTcd5WgtxU0dkhyAjzoKD_s0nTbuNnxm
"""

"""
Regex based rules engine for keywords and phrases that pertain to specific pre-set topics.
Trigger words and phrases ported over from reports. These words and phrases were set up through
a manual learning process by looking at looking at historical comments.
"""

import re